{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-phoenix.fullname" . }}
  namespace: {{ include "kube-phoenix.namespace" . }}
  labels:
    {{- include "kube-phoenix.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "kube-phoenix.databaseUrl" . | quote }}
  ADMIN_USER: {{ .Values.secret.adminUser | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  {{- if .Values.oidc.enabled }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
