{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-phoenix.fullname" . }}
  namespace: {{ include "kube-phoenix.namespace" . }}
  labels:
    {{- include "kube-phoenix.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "kube-phoenix.databaseUrl" . | quote }}
  BASIC_AUTH_USER: {{ .Values.secret.basicAuthUser | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.secret.basicAuthPassword | quote }}
{{- end }}
