apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-phoenix.fullname" . }}
  namespace: {{ include "kube-phoenix.namespace" . }}
  labels:
    {{- include "kube-phoenix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kube-phoenix.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
