apiVersion: v2
name: kube-phoenix
description: Kubernetes cluster sleep/wake schedule manager
type: application
version: 0.5.10
appVersion: 0.5.10
kubeVersion: '>=1.25.0-0'
keywords:
  - kubernetes
  - scaling
  - scheduler
  - cost-optimization
  - sleep-wake
  - scale-to-zero
  - scheduling
  - cloud-native
  - finops
home: https://github.com/MacXsimilian/kube-phoenix
sources:
  - https://github.com/MacXsimilian/kube-phoenix
maintainers:
  - name: MacXsimilian
    url: https://github.com/MacXsimilian
annotations:
  artifacthub.io/license: Apache-2.0
